"""init

Revision ID: 6208a478d8c5
Revises: 
Create Date: 2022-04-29 17:41:19.144906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6208a478d8c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designelement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('designguide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color1', sa.String(length=20), nullable=True),
    sa.Column('color2', sa.String(length=20), nullable=True),
    sa.Column('color3', sa.String(length=20), nullable=True),
    sa.Column('color4', sa.String(length=20), nullable=True),
    sa.Column('color5', sa.String(length=20), nullable=True),
    sa.Column('color6', sa.String(length=20), nullable=True),
    sa.Column('designguide_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['designguide_id'], ['designguide.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('font',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=80), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('designguide_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['designguide_id'], ['designguide.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword1', sa.String(length=80), nullable=True),
    sa.Column('keyword2', sa.String(length=80), nullable=True),
    sa.Column('keyword3', sa.String(length=80), nullable=True),
    sa.Column('keyword4', sa.String(length=80), nullable=True),
    sa.Column('keyword5', sa.String(length=80), nullable=True),
    sa.Column('keyword6', sa.String(length=80), nullable=True),
    sa.Column('designguide_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['designguide_id'], ['designguide.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=80), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('designguide_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['designguide_id'], ['designguide.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('company_email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('designguide_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['designguide_id'], ['designguide.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_company_email'), 'user', ['company_email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_company_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('logo')
    op.drop_table('keyword')
    op.drop_table('font')
    op.drop_table('color')
    op.drop_table('designguide')
    op.drop_table('designelement')
    # ### end Alembic commands ###
