"""desperated try to make the db work

Revision ID: 686e97bf824a
Revises: 8a4cf21b1874
Create Date: 2022-04-21 18:26:44.154902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686e97bf824a'
down_revision = '8a4cf21b1874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('designguide_element', 'font_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('designguide_element', 'design_guide_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('designguide_element', 'keyword_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('designguide_element', 'logo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('designguide_element', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'designguide_element', 'color', ['color_id'], ['id'])
    op.create_foreign_key(None, 'user', 'designguide', ['designguide_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'designguide_element', type_='foreignkey')
    op.alter_column('designguide_element', 'color_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('designguide_element', 'logo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('designguide_element', 'keyword_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('designguide_element', 'design_guide_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('designguide_element', 'font_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
